### PR TITLE
modelling_output_files

### PR DESCRIPTION
**Pull request by alaparicioc**
This issue is to provide the output files of the modelling and the code in R to obtain the input data for the dashboard as agreed when working with the dummy data.

### CODE REVIEW

**Comment by edarin** [comment]
ey @alaparicioc is it possible to have a readme somewhere to explain how to get the modelling output files? I am going to test your files in the dashboard and I dont really understand al those scripts.

**Comment by alaparicioc** [comment]
Hi @edarin,

Hope you had great weekend. Within the following folder [src/analysis/toy_examples/modelling_output_files](https://github.com/OxfordDemSci/UkraineNowPop/tree/0723b82c3955505ce43909a24ef36fe9a4237b17/src/analysis/toy_examples/modelling_output_files) , I included the README file and two csv files with the model output that have the format we agreed with @GISRedeDev for the dashboard. You can use the csv files directly since @GISRedeDev worked the dashbpard based on this format.

Let me know if you need anything else.

Andrea

**Comment by edarin** [comment]
I would need to know in your `sex` colum which sex is 1 and which sex is 2 as in the dashboard population database it is stored as `male` and `female`.

In the migration table I would need two columns: `probability` and `count`. It seems that currently probabilities are designed to sum to 1 across all age, sex and admin unit per day. The dashboard is currently not ready to display any uncertainty linked to the migration estimation.

**Comment by alaparicioc** [comment]
Hi. 
I have updated the README and the output csv files for the dashboard with the labels for sex.

Yes, probabilities are designed to sum to 1 across all age, sex and admin unit per day for now. I am working on how to manage the data from the model to get probabilities for all possible combinations that we need to display.

Please, omit the mob_lower and mob_upper in the previous version. I have deleted the CIs in the current output model. CIs are only needed for the population estimates.

**Comment by edarin** [comment]
Great! Do you think you could add a random `probability` column such that i can test your migration data in the dashboard? Pop data's working fine!

**Comment by edarin** [comment]
And at one point is it possible to have simulated data for the entire Ukraine?

**Pull request merged**
